version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '6603:3306'
      volumes:
      - ./db-seeds:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: barber
        MYSQL_DATABASE: bookber

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db